"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import { InterviewProvider } from "@/context/interviews-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "AI Interview App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <InterviewProvider>
          <div className="flex h-screen">
            {/* Sidebar (client component) */}
            <Sidebar />

            {/* Main content */}
            <div className="flex-1 flex flex-col">
              <main className="flex-1 p-6 bg-white">{children}</main>
            </div>
          </div>
        </InterviewProvider>
      </body>
    </html>
  );
}
